Done

diff --git a/web_server/1-install_ngix_web_server b/web_server/1-install_ngix_web_server
--- a/web_server/1-install_ngix_web_server
+++ b/web_server/1-install_ngix_web_server
@@ -1,32 +1,33 @@
 #!/usr/bin/env bash
-# Configures a new ubuntu machine by installing
-# Nginx where it should be listening on port 80
-# Serve a page that would return a Hello World string
-#
+# Install and configure Nginx web server
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+# Update package lists
+apt-get update
 
-echo -e "\nSetting up some minor stuff.\n"
+# Install Nginx
+apt-get install -y nginx
 
-# starting nginx service
-sudo service nginx start
+# Create a custom Nginx index.html file
+echo "Holberton School" > /var/www/html/index.html
 
-# allowing nginx on firewall
-sudo ufw allow 'Nginx HTTP'
+# Restart Nginx without using systemctl
+service nginx restart
 
-# Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+# Check if Nginx is running and listening on port 80
+if [ "$(lsof -i :80 | grep nginx)" ]; then
+    echo "Nginx is running and listening on port 80."
+else
+    echo "Nginx failed to start or is not listening on port 80."
+    exit 1
+fi
 
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
+# Check if the root page contains the required string
+response=$(curl -sI http://localhost | grep "Holberton School")
+if [ -n "$response" ]; then
+    echo "The root page contains the required string: 'Holberton School'"
+else
+    echo "The root page does not contain the required string: 'Holberton School'"
+    exit 1
+fi
 
-# Creating new index
-echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
-
-# Restarting nginx
-sudo service nginx restart
-
-echo -e "\nCompleted. ✅\n"
+echo "Configuration completed successfully."
